### ISSUE TITLE
dtb image generated here is far too small and does not flash

### ISSUE THREAD

**Issue by frostybeard** [96boards-hikey/tools-images-hikey960#15]
With these build steps, I get a dtb image that is less then 15 kb
and it does not flash with fastboot:
(in the out/target/product/hikey960 folder)
14336 Sep 14 11:34 dt.img

in the device/linaro/hikey-kernel folder, the dtb images are much
bigger:
23076236 Sep 12 11:12 Image-dtb-4.9
these do flash with fastboot.

**Comment by docularxu** [comment]
14336 is reasonable. Mine is 12288.

Image-dtb-4.9 includes both the kernel Image and the dtb, so it's much bigger.

**Comment by frostybeard** [comment]
Hi docularxu,
Is there some extra step that I am missing in order to be able to flash it to the device?
Thanks.

**Comment by frostybeard** [comment]
I figured it out. I copied them over to the device/linaro/hikey-kernel  
folder in the aosp and let the aosp build them. Then I was able to flash them.
