### ISSUE TITLE
Stuck, undefined __stack_chk_guard

### ISSUE THREAD

**Issue by bonben** [96boards-hikey/tools-images-hikey960#17]
Hi, I'm trying to build the uefi for hikey 960. But I'm stuck when I launch the script to build it.
When launchin the uefi_build.sh script from uefi tools, I've got these error messages : 
/home/bonben/Projects/hikey960/ATF_UEFI/edk2/ArmPlatformPkg/PrePi/PrePi.c:55: undefined reference to `__stack_chk_guard'

Here is the output of the script : 

[raw_output.txt](https://github.com/96boards-hikey/tools-images-hikey960/files/1342375/raw_output.txt)

**Comment by fboudra** [comment]
without digging into your specific issue, you can use the CI script instead: https://git.linaro.org/ci/job/configs.git/tree/rpb-uefi/staging/builders.sh

used in https://ci.linaro.org/view/reference-platform/job/96boards-reference-uefi-staging/configure

log: https://ci.linaro.org/view/reference-platform/job/96boards-reference-uefi-staging/MX_PLATFORM=hikey960,MX_TYPE=RELEASE,label=docker-stretch-amd64/24/consoleText

and the latest snapshots is published on https://builds.96boards.org/snapshots/reference-platform/components/uefi-staging/latest/hikey960/release/

I know it doesn't resolve your specific issue but it should get you in the right track.

**Comment by hzhuang1** [comment]
@bonben, I don't know which toolchain you are using. But we need to use GCC newer than 7.1.1. Otherwise, we'll meet some GCC issues.

As Fathi said, you could try the CI script to build it.
