### ISSUE TITLE
No visible progress when running hikey_idt

### ISSUE THREAD

**Issue by ChrisGautier** [96boards-hikey/tools-images-hikey960#23]
Hi,

If I run (as root):
``
 ./hikey_idt -c config -p /dev/ttyUSB0
``

I get:
```
Config name: config
Port name: /dev/ttyUSB0
0: Image: ./sec_usb_xloader.img Downalod Address: 0x20000
1: Image: ./sec_uce_boot.img Downalod Address: 0x6a908000
2: Image: ./sec_fastboot.img Downalod Address: 0x1ac00000
Serial port open successfully!
Start downloading ./sec_usb_xloader.img@0x20000...
file total size 99584
downlaod address 0x20000
```

and the output gets stuck there.

- ``/dev/ttyUSB0`` does work, I can connect to it with e.g. putty
- I have checked that modemmanager is _not_ installed.

Using strace, the log ends with:
```
write(1, "downlaod address 0x20000\n", 25downlaod address 0x20000) = 25
write(4, "\376\0\377\1\0\1\205\0\0\2\0\0\371\200", 14) = 14
read(4,
```

**Comment by hzhuang1** [comment]
There're two usb ports. One is usb serial, and the other is usb otg port configured as serial mode in recovery mode. If two usb cables are connected, the first one is usb serial (ttyUSB0) and the second one is usb OTG port (ttyUSB1). If only one usb cable is used, it should only connect to USB OTG port and be used as ttyUSB0.

So please check that how much usb cables are you connecting to HiKey960 platform first.

**Comment by ChrisGautier** [comment]
That makes sense, I was using the wrong USB port. Thank you!
