### ISSUE TITLE
NVMe issue on HiKey960 and Broken link in README

### ISSUE THREAD

**Issue by melqu1ades** [96boards-hikey/tools-images-hikey960#25]
Hi all,
I have a couple of issues to submit:
1. NVMe issue on HiKey960 board
2. Broken link in README documentation

Details:
1. NVMe issue

We have 2 HiKey960 Ver. B boards. We are trying to use with them some PCIe NVMe Gen 3 x4 SSDs (Kingston KC1000 240GB) through the M.2 connector available on board.
We have used the instructions and material you shared, and installed a Linux root FS as below

`Linux hikey960 4.14.0-rc7-linaro-hikey960 #1 SMP PREEMPT Thu Jan 11 02:07:32 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux`

No chance to get NVMe devices detected in the OS.
```
root@hikey960:~# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sdd       8:48   0 29.8G  0 disk 
|-sdd2    8:50   0   12M  0 part 
|-sdd9    8:57   0    2M  0 part 
|-sdd7    8:55   0   64M  0 part 
|-sdd5    8:53   0  256M  0 part 
|-sdd12   8:60   0    1M  0 part 
|-sdd3    8:51   0    6M  0 part 
|-sdd10   8:58   0  4.6G  0 part /
|-sdd1    8:49   0    1M  0 part 
|-sdd8    8:56   0   16M  0 part 
|-sdd6    8:54   0    1M  0 part 
|-sdd13   8:61   0 24.1G  0 part 
|-sdd4    8:52   0   12M  0 part 
`-sdd11   8:59   0  784M  0 part 
sdb       8:16   0    4M  0 disk 
sdc       8:32   0    8M  0 disk 
`-sdc1    8:33   0    7M  0 part 
sda       8:0    0    4M  0 disk 
```

**Any suggestion to overcome this issue?**

---

2. Broken link
Its related to the previous issue because is in the README page used to run that experiment.

In the following section

Step 5: Explore other modes, proceed to OS installation

- Remove power from the board
- Proceed to OS "Installation" through the [HiKey960 documentation landing page](https://github.com/96boards/documentation/tree/master/ConsumerEdition/HiKey960)

the following link is broken:
https://github.com/96boards/documentation/tree/master/ConsumerEdition/HiKey960

**Can someone fix it?**

Thanks a lot for your support.
Regards,
Guglielmo

**Comment by hzhuang1** [comment]
@melqu1ades Could you help to report issue in https://bugs.96boards.org? If it's logged in the bug system, it's easy to track.

**Comment by docularxu** [comment]
Updated README.md. Thanks for reporting.

**Comment by docularxu** [comment]
Checked Kingston KC1000 240GB, and I found it's 4 lanes. But on HiKey960, the M.2 supports only 1 lane.  I'm not expert on this. But any way, would you evaluate whether it can be compatible on a 1-lane only PCIe M.2 port?

@melqu1ades please open a bug as @hzhuang1 said.

**Comment by melqu1ades** [comment]
Thanks for the broken link fix in README doc.

**Comment by melqu1ades** [comment]
@hzhuang1 Ok. Entered the registration process into bugs.96boards.org.

**Comment by melqu1ades** [comment]
@hzhuang1 @docularxu Bug created on Feb 15, 2018: [link](https://bugs.96boards.org/show_bug.cgi?id=707)
