### ISSUE TITLE
Fails to re-generate dt.img

### ISSUE THREAD

**Issue by cloverpop** [96boards-hikey/tools-images-hikey960#31]
I updated the hikey960 kernel recently and found it fails to re-generate the dt.img

./mkdtimg -d hi3660-hikey960.dtb -s 2048 -c -o dt_test.img
Traceback (most recent call last):
  File "./mkdtimg", line 159, in <module>
    main()
  File "./mkdtimg", line 153, in main
    dtimg_head_info = dt_head_info('HSDT', dtimg_version, dtb_count)
TypeError: expected bytes, str found

**Comment by docularxu** [comment]
This is because you are using python 3.x.
Try python 2.7

**Comment by cloverpop** [comment]
Thanks. It resolved.
