### ISSUE TITLE
HiKey fastboot mode

### ISSUE THREAD

**Issue by elkoniu** [96boards-hikey/tools-images-hikey960#34]
If I restore HiKey960 using:
``$sudo ./hikey_idt -c config -p /dev/ttyUSB1``
I will have fastboot available without power cycle after this steep.
Another option is to set switches (board v2) to ON-OFF-ON and then power cycle.
This will also trigger fastboot access to board.

What is difference between those two situations? If fastboot enabled after usage of **hikey_idt** gives some more access to memory and it is "more powerfull" ?

When I am putting new OP-TEE or AOSP build if there is any difference "which fastboot" I will use?

**Comment by hzhuang1** [comment]
Both of them are fastboot mode. And there's no difference.

In normal boot mode, you could input "ENTER" key on serial console to exit fastboot. Then UEFI will try to boot after exiting fastboot.
In recovery mode, UEFI shouldn't boot kernel. If the user sticks to boot kernel, he will meet kernel hang.

**Comment by elkoniu** [comment]
So there is no difference if I flash new images (via fastboot) directly after board recovery via hikey_idt, or after power cycle with correct set of switches (ON-OFF-ON). I thought that crucial for the board recovery process is to use "this fastboot" enabled after hikey_idt command to put everything in right type of memory.

**Comment by hzhuang1** [comment]
No. hikey_idt can't flush anything. It just download images into board RAM. Only UEFI could flash images via fastboot mode.

**Comment by elkoniu** [comment]
Thank you for answers:)
