### ISSUE TITLE
duplicate scripts: recovery-flash-uefi.sh and install-prebuilt-uefi/hikey960-efi-prebuilt.sh

### ISSUE THREAD

**Issue by v0lker** [96boards-hikey/tools-images-hikey960#39]
it's a bit confusing as they both seem to serve the same purpose, with the latter being a bit more flexible. maybe the latter could be moved to the top-level directory and the first one deleted?

**Comment by hzhuang1** [comment]
@v0lker Maybe you can prepare a patch. Then people could comment/review it.

**Comment by v0lker** [comment]
done that, let me know your thoughts...

**Comment by v0lker** [comment]
fix has been merged => closing
